// <auto-generated />
namespace BELibrary.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class add_new_collumn2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_new_collumn2));
        
        string IMigrationMetadata.Id
        {
            get { return "202107011451457_add_new_collumn2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
